### ISSUE TITLE
Extending DSL

### ISSUE THREAD

**Issue by dbl001** [dkamm/deepcoder#9]
Any thoughts on extending the DSL to incorporate:
i. user defined function(s) from the existing DSL functions and lambdas?
ii. recursion?

Thanks in advance!

**Comment by dkamm** [comment]
I think the tricky part is generating a new dataset with your dsl extensions in the same manner that the paper authors did (which I'm assuming you'd want to do).  You would have to add constraint propagation logic for your new functions to `constraint.py`.  Recall the reason they did that is to keep invalid program/inputs out of their dataset- for instance, `SCAN1L(LPLUS, [255,255])=510` would be invalid if the output range is `[-256,256]`.

Unfortunately, I don't think there's a good way to do this unless you keep your extensions really simple.  For example, if you wanted to add `fibonacci` and the output range is `[-256,256]`, then the input range would be `[0,13]` because the `fib(13)=233` and `fib(14)=377`.  You would have to clip the input range to the largest `n` such that `fib(n)` is in the output range, maybe by precomputing the first 13 fibonacci numbers and using that to check.  One of the benefits of keeping the dsl simple is that it keeps the constraint propagation tractable.

Good luck, let me know if you had any other ideas in mind

**Comment by dbl001** [comment]
Understood.

Other ideas:
1. adjust the DSL so that input and output can be floating point numbers,
2. Add the python math functions to the DSL.
E.g. 

https://docs.python.org/3/library/math.html <https://docs.python.org/3/library/math.html>

**Comment by dkamm** [comment]
If you allow floating point numbers, you'll have an infinite number of possible input/output values and you'll have to change the embedding layer of the neural network.  There are interesting ideas and I encourage you to try them out on your own fork- I want to keep `master` as a faithful implementation of the paper so I'm not going to add any extensions here.
